# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ValidarMedicao
                                 A QGIS plugin
 Valida medições de bacias de captação e terraços executados pela CODEVASF 1SR
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-06-30
        copyright            : (C) 2025 by Givaldo Cavalcanti/CODEVASF
        email                : givaldo.junior@codevasf.gov.br
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ValidarMedicao class from file ValidarMedicao.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .validar_medicao import ValidarMedicao
    return ValidarMedicao(iface)
